services:

  node:
    image:  tulipan81/blind_pin_server:v0.0.4@sha256:6c181140ca4fff76ed56b4ceda2efaef45db43c804bffa6a6b8618e8a63cad14
    depends_on:
      - web
      - tailscale
      - tor
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - $APP_PINSERVER_PORT:$APP_PINSERVER_PORT
    volumes:
      - ${PWD}/data/server_public_key.pub:/server_public_key.pub
      - ${PWD}/data/server_private_key.key:/server_private_key.key
      - ${PWD}/data/pins:/pins

  web: 
    image: tulipan81/pinserver_web:v0.0.32@sha256:764d63e061484c5c492d6653695ee43944d40f645c622719b1ff3281ee38ed10 
    restart: on-failure
    ports:
      - $APP_PINSERVER_WEB_PORT:$APP_PINSERVER_WEB_PORT
    volumes:
      - ${PWD}/data/server_public_key.pub:/app/server_public_key.pub
      - ${PWD}/data/server_private_key.key:/app/server_private_key.key
      - ${PWD}/data/pins:/app/pins
    environment:
      PINSERVER_URL_A: ${APP_PINSERVER_HIDDEN_SERVICE}
      PINSERVER_PORT_A: ${APP_PINSERVER_PORT}
      PINSERVER_URL_B: ${APP_TAILSCALE_URL}
      PINSERVER_PORT_B: ${APP_PINSERVER_PORT}

  tailscale:
    network_mode: "host"
    image: tailscale/tailscale:v1.48.1@sha256:51c756718c30b15d1d3d228b1f4425cba646ec15da5d188a0d55c32b8ea4f378
    restart: on-failure
    stop_grace_period: 1m
    command: "sh -c 'tailscale web --listen 0.0.0.0:8240 & exec tailscaled --tun=userspace-networking'"
    volumes:
      - ${PWD}/data:/var/lib

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${PWD}/data/torrc:/etc/tor/torrc:ro
      - ${PWD}/data:/data
    environment:
      HOME: "/tmp"
